### ISSUE TITLE
代码块，行高亮

### ISSUE THREAD

**Issue by xovel** [xovel/zmd#4]
该功能由于设计原因，现在抽出来进行移除。

***************

部分场景下，需要针对代码块中的指定行数进行高亮显示，以强调该行的重要性。

之前的实现方式思路如下：

1. 在处理 fence code block 的时候，提取出里面高亮行信息。通常这个信息时由花括号包含的一个文本，里面可以直接设置行数，也可以设置一个范围，示例：`{3}` 表示高亮第 5 行；`{5-7}` 表示高亮 5 - 7 行。可以使用逗号分隔设置多个：`{1,4-6, 9}` 表示高亮 1、4、5、6、9 这四行。

2. 在词法分析中，fence 模块中解析该语法。解析函数可以长这样：

```js
function getHLines(text, code) {
  var ret = []
  if (text) {
    var lines = code.split('\n').length
    _each(text.split(/ *, */), function (item) {
      if (item.indexOf('-') === -1) {
        var n = +item
        if (n && n <= lines) {
          ret.push(n)
        }
      } else {
        var nn = item.split(/ *- */)
        for (var i = +nn[0]; i <= +nn[1] && i <= lines; i++) {
          ret.push(i)
        }
      }
    })
  }
  return ret
}
``` 

> 其中 `_each` 为数组遍历方法。
>
> 该方法未对里面的有效性进行验证。

3. 在 parse 操作中，将相关参数传递给渲染器。

4. 在渲染器中进行针对性处理。

```js
...
  if (this.options.highlightLine && hLines && hLines.length > 0) {
    var wrap = ''
    wrap = '<div class="code-hl">\n'
    for (var i = 0; i < hLines.length; i++) {
      wrap += '<div class="code-hl-item" style="top:'
      wrap += ((hLines[i] - 1) * (this.options.highlightHeight || 20) + (this.options.highlightOffsetTop || 16))
      wrap += 'px"></div>\n'
    }

    out = wrap + out + '</div>'
  }
...
```

5. 给予一定的样式支持即可。

```css
/* code highlight lines */
.code-hl {
  position: relative;
  background-color: #f6f8fa;
  border-radius: 3px;
}
.code-hl pre {
  line-height: 20px;
  background: none;
  position: relative;
  z-index: 2;
}
.code-hl-item {
  position: absolute;
  z-index: 1;
  height: 20px; width: 100%;
  background-color: rgba(0, 0, 0, .1);
}
```

由于该功能涉及到的代码量过于繁杂，故此进行移除。GFM 规范中并没有要求解析这类数据。

转移办法为在 fence 词法分析的时候将信息收集起来，parse 的时候将其传入 renderer，通过自定义 renderer 进行实现即可。

相关插件的接入方式在做进一步设计。
